.TH SRISC-DISASM 1 2024-07-11 srisc
.SH NAME
srisc-disasm \- flat SimpleRISC disassembler
.SH SYNOPSIS
.B srisc-disasm
.I FILENAME
.SH DESCRIPTION
.B srisc-disasm
is a flat disassembler for the SimpleRISC ISA.  Disassembly always begins with
the first byte of the given file, and proceeds to disassemble as many
instructions as possible.
.SH SEE ALSO
srisc-emulate(1)
